[package]
name = "svgdom"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.10.4"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "dom"]
license = "MPL-2.0"
description = "Library to represent an SVG as a DOM."
repository = "https://github.com/RazrFalcon/libsvgdom"
documentation = "https://docs.rs/svgdom/"
readme = "README.md"

[badges]
travis-ci = { repository = "RazrFalcon/libsvgdom" }

[dependencies]
log = "0.4"
float-cmp = "0.3"
# simplecss = { git = "https://github.com/RazrFalcon/simplecss.git" }
simplecss = "0.1.0"
# clippy = { version = "*", optional = true }

[dependencies.svgparser]
# latest public
# git = "https://github.com/RazrFalcon/libsvgparser.git"
# branch = "master"
# local copy
# path = "../svgparser"
# from crates
version = "0.6"

[dependencies.error-chain]
version = "0.11"
default-features = false

[dev-dependencies]
time = "0.1"
bencher = "0.1"

[[bench]]
name = "parser"
harness = false

[lib]
doctest = true
